complexity:
  TooManyFunctions:
    active: false

style:
  MaxLineLength:
    active: true
    maxLineLength: 160
    excludePackageStatements: true
    excludeImportStatements: true
    excludeCommentStatements: false
